Title = "nysascape@website:~$"
baseurl = "https://nysascape.digital"
languageCode = "en-gb"
title = "nysascape@website:~$"
theme = "hello-friend-ng"

[params]
  author = "Jago Gardiner"
  homeSubtitle = "Welcome to my website!"
  avatarurl = "https://avatars2.githubusercontent.com/u/23172221?s=460&v=4"
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  keywords = "homepage, blog programming"
  contentTypeName = "posts"
  defaultTheme = "dark"
  copyright = "Copyrights reserved // nysascape"
  [params.logo]
    logoText     = "$ nysascape"
    logoHomeLink = "/"
[languages]
    [languages.en]
      subtitle  = ""
      weight    = 1
      copyright = 'nysascape'
[menu]
  [[menu.main]]
    name = "contact"
    weight = 0
    url = "/contact"
  [[menu.main]]
    name = "works"
    weight = 1
    url = "/works"
  [[menu.main]]
    name = "about me"
    weight = 2
    url = "/about"
  [[menu.main]]
    name = "semaphore"
    weight = 3
    url = "https://semaphoreci.com/nysascape/"
  [[menu.main]]
    name = "posts"
    weight = 4
    url = "/posts"

[[params.social]]
      name = "GitHub"
      icon = "fab fa-github fa-2x"
      url = "https://github.com/nysascape"
[[params.social]]
      name = "Instagram"
      icon = "fab fa-instagram fa-2x"
      url = "https://instagram.com/jagogardiner"
[[params.social]]
      name = "Twitter"
      icon = "fab fa-twitter fa-2x"
      url = "https://twitter.com/nysascape"
